name: Push commit
on: 
  issues:
    types:
      - opened
      - reopened
      - labeled
jobs:
  report:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Generate certificate
        run: |
          echo "Issue: ${{ github.event.issue.number }}" > issue.txt

      - name: Commit files
        run: |
          git config --global user.name 'Codaqui Bot - Github Actions'
          git config --global user.email 'contato@codaqui.dev'
          git add issue.txt
          git commit -m "Issue Number: ${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
          git push

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          reactions: '+1'
          body: |
            Opa, certificado gerado com sucesso!