name: Push commit
on: 
  issues:
    types:
      - opened
      - reopened
      - labeled
jobs:
  report:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Issue Data
        run: |
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue Author: ${{ github.event.issue.user.login }}"
          echo "Issue Assignee: ${{ github.event.issue.assignee.login }}"
          echo "Issue Labels: ${{ github.event.issue.labels }}"
          echo "Issue Milestone: ${{ github.event.issue.milestone.title }}"
          echo "Issue State: ${{ github.event.issue.state }}"
          echo "Issue Created At: ${{ github.event.issue.created_at }}"
          echo "Issue Updated At: ${{ github.event.issue.updated_at }}"
          echo "Issue Closed At: ${{ github.event.issue.closed_at }}"
          echo "Issue URL: ${{ github.event.issue.html_url }}"
          echo "Issue Comments: ${{ github.event.issue.comments }}"
          echo "Issue Reactions: ${{ github.event.issue.reactions }}"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
          
            This is a multi-line test comment automated by GitHub Actions
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
      # - name: Commit files
      #   run: |
      #     git config --global user.name 'Codaqui Bot - Github Actions'
      #     git config --global user.email 'contato@codaqui.dev'
      #     git add report.txt
      #     git commit -m "Issue Number: ${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
      #     git push